name-template: "Philip De Lorenzo -- Helium API Client v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "ğŸš€ Features"
    label: "feature"
  - title: "ğŸ› Bug Fixes"
    labels: "fix"
  - title: "ğŸ”¥ Hot Fixes"
    label: "hotfix"
  - title: "ğŸš… Performance"
    label: "performance"
  - title: "ğŸ˜ Refactor"
    label: "refactor"
  - title: "ğŸ§° Maintenance"
    labels:
      - "chore"
      - "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Philip De Lorenzo - Helium API Client Release Notes

  #### Philip De Lorenzo - Helium API Client v$RESOLVED_VERSION

  *This is the official release of Helium API Client version $RESOLVED_VERSION.*
  This tool is designed for testing purposes only, and to showcase the manner in which I work as a Platform Engineer/DevOps/SRE/Developer.

  -- *Philip De Lorenzo - Platform Engineer*

  [Example](https://github.com/philipdelorenzo/fuzzy-helium-meme)


  ## Changes

  $CHANGES

  ## Installation

  ```bash
  # Install the latest version of the Helium API Client
  More coming soon...
  ```
  